# Generated by Django 3.2.21 on 2023-10-04 12:23

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20231004_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
