# Generated by Django 3.2.21 on 2023-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231011_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
